examen3/config/routes.rb
Rails.application.routes.draw do
  resources :people do
    resources :document
    resources :roles
  end

  root 'people#index'
end

examen3/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

examen3/app/models/document.rb
class Document < ApplicationRecord
  has_many :people
end

examen3/app/models/person.rb
class Person < ApplicationRecord
    belongs_to :document
    belongs_to :role
end

examen3/app/models/role.rb
class Role < ApplicationRecord
  has_many :people
end

examen3/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

examen3/app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]


  def index
    @people = Person.all
  end


  def new
    @person = Person.new
  end
  
  
  def show
  end

  
  def edit
  end


  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Persona registrada exitosamente.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Datos actualizados exitosamente.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Persona elimindad correctamente.' }
      format.json { head :no_content }
    end
  end

  private
    
    def set_person
      @person = Person.find(params[:id])
    end

    def person_params
      params.require(:person).permit(:identification, :first_name, :second_name, :first_last_name, :second_last_name, :document_id, :role_id)
    end
end

examen3/app/helpers/application_helper.rb
module ApplicationHelper
end

examen3/app/helpers/people_helper.rb
module PeopleHelper
end

examen3/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Proyecto</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  

  <body>
  <header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Home</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#"><span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#"></a>
        </li>
       
        <li class="nav-item">
          <a class="nav-link disabled" href="#"></a>  
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">        
      </form>
    </div>
    </nav>  
  </header>
  <main class = "container">
   <section class = "row">
    <aside class="col-md-4">
      <div class="list-group">
        <%= link_to 'People', people_path, class:"list-group-item list-group-item-action" %>
        <%= link_to 'New Person', new_person_path, class:"list-group-item list-group-item-action" %>
        <li class="list-group-item list-group-item-action">Option 1</li>
        <li class="list-group-item list-group-item-action"> Option 2</li>      
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      </div>
    </aside>
    <articule class="col-md-8"><%= yield %></articule>
   </section>
  </main>
  </body>
  <footer></footer>
</html>

examen3/app/views/people/_form.html.erb
<div class="row">
  <div class="col-md-7">
    <%= simple_form_for @person, html: {class: "form-horizontal"} do |f| %>
      <div class="form-group">
        <%= f.input :identification, input_html: {class: "form-control"} %>
      </div>

      <div class="form-group">
        <%= f.input :first_name, input_html: {class: "form-control"} %>
      </div>

      <div class="form-group">
        <%= f.input :second_name, input_html: {class: "form-control"} %>
      </div>

      <div class="form-group">
        <%= f.input :first_last_name, input_html: {class: "form-control"} %>
      </div>

      <div class="form-group">
        <%= f.input :second_last_name, input_html: {class: "form-control"} %>
      </div>
      
      <%= f.association :document, label_method: :document_type, input_html: {class: "form-control"} %>
      <%= f.association :role, label_method: :role_name, input_html: {class: "form-control"} %>



      <div class="form-group">
        <%= f.button :submit, class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

examen3/app/views/people/_person.html.erb
<tr>
  <td><%= person.id %></td>
  <td><%= link_to person.identification, person_path(person) %></td>
  <td><%= person.first_name %></td>
  <td><%= person.second_name %></td>
  <td><%= person.first_last_name %></td>
  <td><%= person.second_last_name %></td>
  <td><%= person.document.document_type %></td>
  <td><%= person.role.role_name %></td>
</tr>

examen3/app/views/people/edit.html.erb
<h1>Editar personas</h1>

<%= render 'form' %>

examen3/app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>People</h1>

<table class="table">
  <thead>
    <tr>
      <th>Document_type</th>
      <th>Identification</th>
      <th>First_name</th>
      <th>Second_name</th>
      <th>First_last_name</th>
      <th>Second_last_name</th>
      <th>Role</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.document.document_type %></td>
        <td><%= person.identification %></td>
        <td><%= person.first_name %></td>
        <td><%= person.second_name %></td>
        <td><%= person.first_last_name %></td>
        <td><%= person.second_last_name %></td>
        <td><%= person.role.role_name %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Person', new_person_path %>

examen3/app/views/people/new.html.erb
<h1>Crear personas</h1>

<%= render 'form' %>

examen3/app/views/people/show.html.erb
show: <h1>Datos de persona</h1>

<dl>
    <dt>Identification</dt>
    <dd><%= @person.identification %></dd>
    <dt>First_name</dt>
    <dd><%= @person.first_name %></dd>
    <dt>Second_name</dt>
    <dd><%= @person.second_name %></dd>
    <dt>First_last_name</dt>
    <dd><%= @person.first_last_name %></dd>
    <dt>Second_last_name</dt>
    <dd><%= @person.second_last_name %></dd>
    <dt>Document</dt>
    <dd><%= @person.document.document_type%></dd>
    <dt>Role</dt>
    <dd><%= @person.role.role_name %></dd>
    
    
</dl>

<%= link_to "Adicionar persona", people_path, class: "btn btn-primary" %>
<br>
</br>
<%= link_to "Editar personas", edit_person_path(@person), class: "btn btn-primary" %>